import json

# Full 68-Item Database
ITEMS = {
    # Attack (17 Items)
    "2011": { "id": 2011, "name": "Blade of Despair", "category": "ATTACK", "price": 3010, "tier": 3, "stats": { "physical_attack": 160, "move_speed_pct": 5 }, "passive": { "name": "Despair", "exclusive_group": "DESPAIR", "description": "+25% Physical Attack vs targets below 50% HP for 2s" } },
    "2002": { "id": 2002, "name": "Demon Hunter Sword", "category": "ATTACK", "price": 2180, "tier": 3, "stats": { "physical_attack": 35, "attack_speed_pct": 25 }, "passive": { "name": "Devour", "exclusive_group": "DEVOUR", "description": "8% current HP as physical damage + 3% lifesteal per hit (up to 15%)" } },
    "2003": { "id": 2003, "name": "Malefic Roar", "category": "ATTACK", "price": 2060, "tier": 3, "stats": { "physical_attack": 60, "physical_pen_pct": 20 }, "passive": { "name": "Armor Buster", "exclusive_group": "ARMOR_BUSTER", "description": "+0.05% Physical Pen per enemy Armor point (max 20%)" } },
    "2005": { "id": 2005, "name": "Windtalker", "category": "ATTACK", "price": 1820, "tier": 3, "stats": { "attack_speed_pct": 40, "move_speed": 20, "crit_rate_pct": 10 }, "passive": { "name": "Typhoon", "exclusive_group": "TYPHOON", "description": "Splash magic damage hitting up to 3 enemies" } },
    "2023": { "id": 2023, "name": "Wind of Nature", "category": "ATTACK", "price": 1910, "tier": 3, "stats": { "physical_attack": 30, "attack_speed_pct": 20, "lifesteal_pct": 10 }, "active": { "name": "Wind Chant", "cooldown_s": 70, "duration_marksman_s": 2.0, "duration_non_marksman_s": 1.0, "description": "Immune to physical damage" } },
    "2001": { "id": 2001, "name": "Berserker's Fury", "category": "ATTACK", "price": 2250, "tier": 3, "stats": { "physical_attack": 65, "crit_rate_pct": 25, "crit_damage_pct": 40 }, "passive": { "name": "Doom", "exclusive_group": "DOOM", "description": "+5% Physical Attack on crit" } },
    "2004": { "id": 2004, "name": "Haas' Claws", "category": "ATTACK", "price": 2020, "tier": 3, "stats": { "physical_attack": 30, "attack_speed_pct": 20, "crit_rate_pct": 20, "lifesteal_pct": 25 }, "passive": { "name": "Frenzy", "exclusive_group": "FRENZY", "description": "+20% Attack Speed on crit" } },
    "2008": { "id": 2008, "name": "Endless Battle", "category": "ATTACK", "price": 2470, "tier": 3, "stats": { "physical_attack": 65, "hp": 250, "cooldown_reduction_pct": 10, "hybrid_lifesteal_pct": 8, "move_speed_pct": 5, "mana_regen": 5 }, "passive": { "name": "Divine Justice", "exclusive_group": "DIVINE_JUSTICE", "description": "60% Physical Attack True Damage after skill + 10% MS" } },
    "2006": { "id": 2006, "name": "Corrosion Scythe", "category": "ATTACK", "price": 2050, "tier": 3, "stats": { "physical_attack": 30, "attack_speed_pct": 35, "move_speed_pct": 5 }, "passive": { "name": "Corrosion", "exclusive_group": "CORROSION", "description": "Basic attacks slow enemy by 8% (up to 40%) + 6% AS per hit" } },
    "2007": { "id": 2007, "name": "Golden Staff", "category": "ATTACK", "price": 2000, "tier": 3, "stats": { "physical_attack": 55, "attack_speed_pct": 15 }, "passive": { "name": "Endless Strike", "exclusive_group": "ENDLESS_STRIKE", "description": "Converts crit rate to attack speed; every 3rd attack procs on-hit twice" } },
    "2009": { "id": 2009, "name": "Rose Gold Meteor", "category": "ATTACK", "price": 2120, "tier": 3, "stats": { "physical_attack": 60, "magic_defense": 23, "lifesteal_pct": 10 }, "passive": { "name": "Lifeline", "exclusive_group": "LIFELINE", "cooldown_s": 40, "description": "Gains shield + magic defense when HP drops below 30%" } },
    "2010": { "id": 2010, "name": "Sea Halberd", "category": "ATTACK", "price": 2050, "tier": 3, "stats": { "physical_attack": 80, "attack_speed_pct": 20 }, "passive": { "name": "Lifebane", "exclusive_group": "LIFEBANE", "description": "-50% healing/shield on target + 8% damage vs higher extra HP" } },
    "2012": { "id": 2012, "name": "Hunter Strike", "category": "ATTACK", "price": 2010, "tier": 3, "stats": { "physical_attack": 80, "cooldown_reduction_pct": 10, "physical_pen_flat": 15 }, "passive": { "name": "Retribution", "exclusive_group": "HUNTER_RETRIBUTION", "cooldown_s": 8, "description": "+50% Movement Speed after 5 consecutive hits" } },
    "2013": { "id": 2013, "name": "Blade of the Heptaseas", "category": "ATTACK", "price": 1950, "tier": 3, "stats": { "physical_attack": 70, "hp": 250, "physical_pen_flat": 15 }, "passive": { "name": "Ambush", "exclusive_group": "AMBUSH", "description": "Next basic attack deals 160 + 40% AD bonus damage and 40% slow" } },
    "2014": { "id": 2014, "name": "War Axe", "category": "ATTACK", "price": 2100, "tier": 3, "stats": { "physical_attack": 25, "hp": 550, "cooldown_reduction_pct": 10, "spell_vamp_pct": 12 }, "passive": { "name": "Fighting Spirit", "exclusive_group": "FIGHTING_SPIRIT", "description": "Stacking AD and Spell Vamp; max stacks grant 10% True Damage" } },
    "2015": { "id": 2015, "name": "Bloodlust Axe", "category": "ATTACK", "price": 1970, "tier": 3, "stats": { "physical_attack": 70, "cooldown_reduction_pct": 10, "spell_vamp_pct": 20 }, "passive": { "name": "Bloodlust", "exclusive_group": "BLOODLUST", "description": "+20% Spell Vamp" } },
    "2016": { "id": 2016, "name": "Great Dragon Spear", "category": "ATTACK", "price": 2140, "tier": 3, "stats": { "physical_attack": 70, "cooldown_reduction_pct": 10, "crit_rate_pct": 20 }, "passive": { "name": "Supreme Warrior", "exclusive_group": "SUPREME_WARRIOR", "cooldown_s": 15, "description": "+30% Move Speed on Ultimate" } },

    # Magic (13 Items)
    "1051": { "id": 1051, "name": "Holy Crystal", "category": "MAGIC", "price": 2180, "tier": 3, "stats": { "magic_power": 100 }, "passive": { "name": "Mystery", "exclusive_group": "MYSTERY", "description": "+21%-35% Magic Power scaling with level" } },
    "1052": { "id": 1052, "name": "Lightning Truncheon", "category": "MAGIC", "price": 2250, "tier": 3, "stats": { "magic_power": 75, "mana": 400, "cooldown_reduction_pct": 10 }, "passive": { "name": "Resonate", "exclusive_group": "RESONATE", "cooldown_s": 6, "description": "Bonus magic bounce damage scaling with max mana" } },
    "1053": { "id": 1053, "name": "Glowing Wand", "category": "MAGIC", "price": 2200, "tier": 3, "stats": { "magic_power": 75, "hp": 400, "move_speed_pct": 5 }, "passive": { "name": "Scorch", "exclusive_group": "SCORCH", "description": "1.5% Max HP burn per second for 3s + 50% anti-heal" } },
    "1054": { "id": 1054, "name": "Divine Glaive", "category": "MAGIC", "price": 1970, "tier": 3, "stats": { "magic_power": 65, "magic_pen_pct": 40 }, "passive": { "name": "Spellbreaker", "exclusive_group": "SPELLBREAKER", "description": "+0.1% Magic Pen per enemy Magic Defense (max 20%)" } },
    "1055": { "id": 1055, "name": "Blood Wings", "category": "MAGIC", "price": 3000, "tier": 3, "stats": { "magic_power": 175, "hp": 500 }, "passive": { "name": "Guard", "exclusive_group": "BLOOD_GUARD", "description": "800 + 100% AP shield + 30 Move Speed when broken" } },
    "1056": { "id": 1056, "name": "Genius Wand", "category": "MAGIC", "price": 2000, "tier": 3, "stats": { "magic_power": 75, "move_speed_pct": 5, "magic_pen_flat": 10 }, "passive": { "name": "Magic Shred", "exclusive_group": "MAGIC_SHRED", "description": "Reduces target Magic Defense by 3-7 per hit (max 3 stacks)" } },
    "1057": { "id": 1057, "name": "Clock of Destiny", "category": "MAGIC", "price": 1950, "tier": 3, "stats": { "magic_power": 60, "hp": 500, "mana": 600 }, "passive": { "name": "Time", "exclusive_group": "TIME", "description": "Gain HP and AP every 20s (max 10 stacks)" } },
    "1058": { "id": 1058, "name": "Concentrated Energy", "category": "MAGIC", "price": 2020, "tier": 3, "stats": { "magic_power": 70, "hp": 700, "hybrid_lifesteal_pct": 20 }, "passive": { "name": "Recharge", "exclusive_group": "RECHARGE", "description": "Dealing magic damage stacks AP; max stacks grant +10% Magic Damage" } },
    "1059": { "id": 1059, "name": "Ice Queen Wand", "category": "MAGIC", "price": 2240, "tier": 3, "stats": { "magic_power": 75, "mana": 300, "move_speed_pct": 7, "spell_vamp_pct": 10 }, "passive": { "name": "Ice Bound", "exclusive_group": "ICE_BOUND", "description": "Skills slow enemy by 10% (up to 30%)" } },
    "1060": { "id": 1060, "name": "Feather of Heaven", "category": "MAGIC", "price": 2030, "tier": 3, "stats": { "magic_power": 55, "attack_speed_pct": 30, "cooldown_reduction_pct": 5 }, "passive": { "name": "Affliction", "exclusive_group": "AFFLICTION", "description": "Basic attacks deal 50 + 30% AP extra magic damage" } },
    "1061": { "id": 1061, "name": "Starlium Scythe", "category": "MAGIC", "price": 2220, "tier": 3, "stats": { "magic_power": 70, "cooldown_reduction_pct": 10, "hybrid_lifesteal_pct": 8, "mana_regen": 6 }, "passive": { "name": "Crisis", "exclusive_group": "CRISIS", "description": "100 + 100% AP True Damage after skill + 10% Move Speed" } },
    "1062": { "id": 1062, "name": "Enchanted Talisman", "category": "MAGIC", "price": 1870, "tier": 3, "stats": { "magic_power": 50, "hp": 250, "cooldown_reduction_pct": 20 }, "passive": { "name": "Mana Spring", "exclusive_group": "MANA_SPRING", "description": "15% Max Mana regen every 10s + 5% max CDR cap" } },
    "1063": { "id": 1063, "name": "Winter Crown", "category": "MAGIC", "price": 1910, "tier": 3, "stats": { "magic_power": 60, "physical_defense": 25, "hp": 400 }, "active": { "name": "Frozen", "cooldown_s": 100, "duration_s": 2.0, "description": "Frozen and invulnerable for 2.0s" } },

    # Defense (12 Items)
    "3001": { "id": 3001, "name": "Athena's Shield", "category": "DEFENSE", "price": 2150, "tier": 3, "stats": { "hp": 900, "magic_defense": 62, "hp_regen": 2 }, "passive": { "name": "Shield", "exclusive_group": "ATHENA_SHIELD", "description": "-25% incoming magic damage for 3s (5s CD out of combat)" } },
    "3002": { "id": 3002, "name": "Antique Cuirass", "category": "DEFENSE", "price": 2170, "tier": 3, "stats": { "hp": 920, "physical_defense": 54, "hp_regen": 4 }, "passive": { "name": "Deter", "exclusive_group": "DETER", "description": "-8% enemy physical attack on skill hit (max 3 stacks = 24%)" } },
    "3003": { "id": 3003, "name": "Dominance Ice", "category": "DEFENSE", "price": 2010, "tier": 3, "stats": { "mana": 500, "physical_defense": 70, "move_speed_pct": 5 }, "passive": { "name": "Arctic Cold", "exclusive_group": "ARCTIC_COLD", "description": "-70% enemy attack speed aura, -50% healing/shield aura" } },
    "3004": { "id": 3004, "name": "Immortality", "category": "DEFENSE", "price": 2120, "tier": 3, "stats": { "hp": 800, "physical_defense": 20 }, "passive": { "name": "Immortal", "exclusive_group": "IMMORTAL", "cooldown_s": 210, "description": "Resurrect 2.5s after death with 16% HP + 220-1200 shield" } },
    "3005": { "id": 3005, "name": "Radiant Armor", "category": "DEFENSE", "price": 1880, "tier": 3, "stats": { "hp": 950, "magic_defense": 52, "hp_regen": 12 }, "passive": { "name": "Holy Blessing", "exclusive_group": "HOLY_BLESSING", "description": "Continuous magic damage grants flat magic reduction per stack" } },
    "3006": { "id": 3006, "name": "Blade Armor", "category": "DEFENSE", "price": 1960, "tier": 3, "stats": { "physical_defense": 90, "crit_damage_reduction_pct": 20 }, "passive": { "name": "Bladed Armor", "exclusive_group": "BLADED_ARMOR", "description": "Reflects 25% physical basic attack damage + 25% defense to attacker" } },
    "3007": { "id": 3007, "name": "Oracle", "category": "DEFENSE", "price": 2060, "tier": 3, "stats": { "hp": 850, "magic_defense": 42, "physical_defense": 25, "cooldown_reduction_pct": 10 }, "passive": { "name": "Bless", "exclusive_group": "ORACLE_BLESS", "description": "+30% shield and HP regen received" } },
    "3008": { "id": 3008, "name": "Brute Force Breastplate", "category": "DEFENSE", "price": 1870, "tier": 3, "stats": { "hp": 600, "physical_defense": 23, "magic_defense": 23, "cooldown_reduction_pct": 10 }, "passive": { "name": "Brute Force", "exclusive_group": "BRUTE_FORCE", "description": "Grants AD, AP, Move Speed, and 15% CC resilience" } },
    "3009": { "id": 3009, "name": "Guardian Helmet", "category": "DEFENSE", "price": 2200, "tier": 3, "stats": { "hp": 1550, "hp_regen": 20 }, "passive": { "name": "Recovery", "exclusive_group": "RECOVERY", "description": "Regenerates 2.5% Max HP/s out of combat" } },
    "3010": { "id": 3010, "name": "Twilight Armor", "category": "DEFENSE", "price": 2100, "tier": 3, "stats": { "hp": 1200, "physical_defense": 20 }, "passive": { "name": "Twilight", "exclusive_group": "TWILIGHT", "description": "Reduces physical burst damage above 600 + True Damage proc" } },
    "3011": { "id": 3011, "name": "Thunder Belt", "category": "DEFENSE", "price": 1990, "tier": 3, "stats": { "hp": 800, "mana": 400, "physical_defense": 30, "magic_defense": 30, "cooldown_reduction_pct": 10 }, "passive": { "name": "Thunderbolt", "exclusive_group": "THUNDERBOLT", "description": "Basic attacks deal True Damage and permanently stack +1 Hybrid Defense" } },
    "3012": { "id": 3012, "name": "Cursed Helmet", "category": "DEFENSE", "price": 1760, "tier": 3, "stats": { "hp": 1200, "magic_defense": 25 }, "passive": { "name": "Burning Soul", "exclusive_group": "BURNING_SOUL", "description": "1.2% Max HP magic damage/s to nearby enemies" } },

    # Movement Boots (7 Items)
    "4001": { "id": 4001, "name": "Warrior Boots", "category": "MOVEMENT", "price": 720, "tier": 2, "stats": { "move_speed": 40, "physical_defense": 22 }, "passive": { "name": "Valor", "exclusive_group": "VALOR", "description": "+5 Physical Defense per physical hit received (up to +25)" } },
    "4002": { "id": 4002, "name": "Tough Boots", "category": "MOVEMENT", "price": 700, "tier": 2, "stats": { "move_speed": 40, "magic_defense": 22 }, "passive": { "name": "Fortitude", "exclusive_group": "FORTITUDE", "description": "Reduces CC and slow durations by 30%" } },
    "4003": { "id": 4003, "name": "Magic Shoes", "category": "MOVEMENT", "price": 710, "tier": 2, "stats": { "move_speed": 40, "cooldown_reduction_pct": 10 } },
    "4004": { "id": 4004, "name": "Arcane Boots", "category": "MOVEMENT", "price": 690, "tier": 2, "stats": { "move_speed": 40, "magic_pen_flat": 10 } },
    "4005": { "id": 4005, "name": "Swift Boots", "category": "MOVEMENT", "price": 710, "tier": 2, "stats": { "move_speed": 40, "attack_speed_pct": 15 } },
    "4006": { "id": 4006, "name": "Rapid Boots", "category": "MOVEMENT", "price": 750, "tier": 2, "stats": { "move_speed": 70 }, "passive": { "name": "Side Effect", "exclusive_group": "SIDE_EFFECT", "description": "-25 Move Speed in combat for 5s" } },
    "4007": { "id": 4007, "name": "Demon Shoes", "category": "MOVEMENT", "price": 720, "tier": 2, "stats": { "move_speed": 40, "mana_regen": 10 }, "passive": { "name": "Mysticism", "exclusive_group": "MYSTICISM", "description": "Mana restore on hero/minion kill" } },

    # Roaming Blessings (4 Items)
    "5001": { "id": 5001, "name": "Roam: Conceal", "category": "ROAMING", "price": 0, "tier": 3, "active": { "name": "Conceal", "cooldown_s": 80, "duration_s": 5, "description": "Grants camouflage and +30%-75% Move Speed to nearby allies for 5s" } },
    "5002": { "id": 5002, "name": "Roam: Encourage", "category": "ROAMING", "price": 0, "tier": 3, "passive": { "name": "Encourage", "exclusive_group": "ROAM_ENCOURAGE", "description": "Aura: +12-18 Physical Attack/Magic Power and +15% Attack Speed to nearby allies" } },
    "5003": { "id": 5003, "name": "Roam: Favor", "category": "ROAMING", "price": 0, "tier": 3, "passive": { "name": "Favor", "exclusive_group": "ROAM_FAVOR", "cooldown_s": 10, "description": "Healing/shielding restores an extra 300-750 HP to lowest HP ally" } },
    "5004": { "id": 5004, "name": "Roam: Dire Hit", "category": "ROAMING", "price": 0, "tier": 3, "passive": { "name": "Dire Hit", "exclusive_group": "ROAM_DIRE_HIT", "cooldown_s": 30, "description": "Attacking an enemy below 35% HP deals 7%-18% Max HP extra hybrid damage" } },

    # Core Components (15 Items)
    "601": { "id": 601, "name": "Dagger", "category": "COMPONENT", "price": 250, "tier": 1, "stats": { "physical_attack": 15 } },
    "602": { "id": 602, "name": "Legion Sword", "category": "COMPONENT", "price": 910, "tier": 2, "stats": { "physical_attack": 60 } },
    "603": { "id": 603, "name": "Vampire Mallet", "category": "COMPONENT", "price": 400, "tier": 1, "stats": { "physical_attack": 8, "lifesteal_pct": 8 } },
    "604": { "id": 604, "name": "Javelin", "category": "COMPONENT", "price": 380, "tier": 1, "stats": { "crit_rate_pct": 8 } },
    "605": { "id": 605, "name": "Knife", "category": "COMPONENT", "price": 280, "tier": 1, "stats": { "attack_speed_pct": 10 } },
    "606": { "id": 606, "name": "Regular Spear", "category": "COMPONENT", "price": 600, "tier": 2, "stats": { "physical_attack": 20, "attack_speed_pct": 10 } },
    "607": { "id": 607, "name": "Mystery Codex", "category": "COMPONENT", "price": 300, "tier": 1, "stats": { "magic_power": 15 } },
    "608": { "id": 608, "name": "Magic Wand", "category": "COMPONENT", "price": 820, "tier": 2, "stats": { "magic_power": 45 } },
    "609": { "id": 609, "name": "Tome of Evil", "category": "COMPONENT", "price": 950, "tier": 2, "stats": { "magic_power": 35, "cooldown_reduction_pct": 8 } },
    "610": { "id": 610, "name": "Power Crystal", "category": "COMPONENT", "price": 220, "tier": 1, "stats": { "mana": 280 } },
    "611": { "id": 611, "name": "Leather Armor", "category": "COMPONENT", "price": 220, "tier": 1, "stats": { "physical_defense": 15 } },
    "612": { "id": 612, "name": "Silence Robe", "category": "COMPONENT", "price": 1020, "tier": 2, "stats": { "hp": 540, "magic_defense": 30 } },
    "613": { "id": 613, "name": "Healing Necklace", "category": "COMPONENT", "price": 140, "tier": 1, "stats": { "hp_regen": 2 } },
    "614": { "id": 614, "name": "Vitality Crystal", "category": "COMPONENT", "price": 300, "tier": 1, "stats": { "hp": 230 } },
    "615": { "id": 615, "name": "Boots", "category": "COMPONENT", "price": 250, "tier": 1, "stats": { "move_speed": 20 } }
}

with open("/data/data/com.termux/files/home/veminsEsp/knowledge/normalized/items.json", "w") as f:
    json.dump(ITEMS, f, indent=2)

print(f"Successfully wrote {len(ITEMS)} complete items into items.json!")
