#!/usr/bin/env python3
"""
VeminsESP Web UI Designer & Live Sandbox Server
Runs locally on Termux/Linux to provide a real-time browser interface
for inspecting, hand-designing, and previewing the overlay and floating menu.
"""

import http.server
import socketserver
import os
import json
import sys
import mimetypes
from urllib.parse import urlparse

PORT = 8888
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PUBLIC_DIR = os.path.join(BASE_DIR, "public")
PROJECT_ROOT = os.path.abspath(os.path.join(BASE_DIR, ".."))
CONFIG_FILE = os.path.join(PROJECT_ROOT, "minimap_config.json")
DESIGN_FILE = os.path.join(BASE_DIR, "custom_design.json")
FEEDBACK_FILE = os.path.join(BASE_DIR, "ui_feedback.json")

mimetypes.add_type("text/javascript", ".js")
mimetypes.add_type("text/css", ".css")
mimetypes.add_type("image/svg+xml", ".svg")
mimetypes.add_type("image/png", ".png")
mimetypes.add_type("application/json", ".json")


class DesignerHandler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=PUBLIC_DIR, **kwargs)

    def do_GET(self):
        parsed = urlparse(self.path)
        path = parsed.path

        if path == "/api/config":
            self.handle_get_config()
        elif path == "/api/design":
            self.handle_get_design()
        elif path == "/api/feedback":
            self.handle_get_feedback()
        elif path == "/api/export-xml":
            self.handle_export_xml()
        else:
            super().do_GET()

    def do_POST(self):
        parsed = urlparse(self.path)
        path = parsed.path
        content_len = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(content_len) if content_len > 0 else b"{}"

        try:
            data = json.loads(body.decode("utf-8"))
        except Exception:
            data = {}

        if path == "/api/config":
            self.handle_post_config(data)
        elif path == "/api/design":
            self.handle_post_design(data)
        elif path == "/api/feedback":
            self.handle_post_feedback(data)
        else:
            self.send_response(404)
            self.end_headers()

    def handle_get_config(self):
        if os.path.exists(CONFIG_FILE):
            try:
                with open(CONFIG_FILE, "r") as f:
                    cfg = json.load(f)
            except Exception:
                cfg = {}
        else:
            cfg = {}
        self.send_json(cfg)

    def handle_post_config(self, data):
        try:
            with open(CONFIG_FILE, "w") as f:
                json.dump(data, f, indent=2)
            self.send_json({"status": "ok", "message": "Config saved successfully"})
        except Exception as e:
            self.send_json({"status": "error", "message": str(e)}, status=500)

    def handle_get_design(self):
        if os.path.exists(DESIGN_FILE):
            try:
                with open(DESIGN_FILE, "r") as f:
                    design = json.load(f)
            except Exception:
                design = self.get_default_design()
        else:
            design = self.get_default_design()
        self.send_json(design)

    def handle_post_design(self, data):
        try:
            with open(DESIGN_FILE, "w") as f:
                json.dump(data, f, indent=2)
            self.send_json({"status": "ok", "message": "Design saved successfully"})
        except Exception as e:
            self.send_json({"status": "error", "message": str(e)}, status=500)

    def handle_get_feedback(self):
        if os.path.exists(FEEDBACK_FILE):
            try:
                with open(FEEDBACK_FILE, "r") as f:
                    feedback = json.load(f)
            except Exception:
                feedback = []
        else:
            feedback = []
        self.send_json(feedback)

    def handle_post_feedback(self, data):
        entries = []
        if os.path.exists(FEEDBACK_FILE):
            try:
                with open(FEEDBACK_FILE, "r") as f:
                    entries = json.load(f)
            except Exception:
                entries = []
        entries.append(data)
        try:
            with open(FEEDBACK_FILE, "w") as f:
                json.dump(entries, f, indent=2)
            self.send_json({"status": "ok", "count": len(entries)})
        except Exception as e:
            self.send_json({"status": "error", "message": str(e)}, status=500)

    def handle_export_xml(self):
        design = self.get_default_design()
        if os.path.exists(DESIGN_FILE):
            try:
                with open(DESIGN_FILE, "r") as f:
                    design = json.load(f)
            except Exception:
                pass

        xml_colors = f"""<!-- res/values/colors.xml snippet generated by Web UI Studio -->
<color name="imgui_bg">{design.get("windowBg", "#1E1E24")}</color>
<color name="imgui_header">{design.get("headerBg", "#2A2B36")}</color>
<color name="imgui_border">{design.get("borderColor", "#3F4152")}</color>
<color name="imgui_accent_cyan">{design.get("accentCyan", "#00E5FF")}</color>
<color name="imgui_button">{design.get("buttonBg", "#2A2C38")}</color>
"""
        self.send_json({"status": "ok", "colorsXml": xml_colors})

    def send_json(self, data, status=200):
        content = json.dumps(data).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(content)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(content)

    def get_default_design(self):
        return {
            "theme": "imgui_slate",
            "windowBg": "#1E1E24",
            "headerBg": "#2A2B36",
            "borderColor": "#3F4152",
            "accentCyan": "#00E5FF",
            "accentGreen": "#00E676",
            "buttonBg": "#2A2C38",
            "buttonHoverBg": "#3B3E4D",
            "textPrimary": "#EEEEF2",
            "textSecondary": "#A0A2B0",
            "borderRadius": 4,
            "cardWidth": 290,
            "headerHeight": 32,
            "puckWidth": 56,
            "puckHeight": 32,
            "fontSize": 11,
            "notes": ""
        }


def run_server(port=PORT):
    if len(sys.argv) > 1:
        try:
            port = int(sys.argv[1])
        except ValueError:
            pass
    socketserver.TCPServer.allow_reuse_address = True
    for p in [port, 9090, 8000, 5000, 3000]:
        try:
            with socketserver.TCPServer(("0.0.0.0", p), DesignerHandler) as httpd:
                print(f"[+] VeminsESP Web UI Studio running at:")
                print(f"    Local (on device): http://localhost:{p}")
                print(f"    Local Network:     http://0.0.0.0:{p}")
                sys.stdout.flush()
                httpd.serve_forever()
                break
        except OSError as e:
            print(f"[-] Port {p} busy ({e}), trying next port...")
            continue


if __name__ == "__main__":
    run_server()
